AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  canary-template:
  - Sample SAM Template for version, alias, canary deploy and API/Lambda alarms
  - Inform Slack channel
  
Parameters:
  EnvType:
    Description: 'Set environment types'
    Type: 'String'
    Default: 'stage'
    AllowedValues: [stage, prod, dev]

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    # enable CORS; to make more specific, change the origin wildcard
    # to a particular domain name, e.g. "'www.example.com'"
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Resources:
  AlarmTopic:
    Type: AWS::SNS::Topic

  HelloWorldAPI:
    Type: AWS::Serverless::Api
    Properties:
        #Name: store-data-app
        StageName: !Ref EnvType 

  LamdbaToSlackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda-to-slack/
      Handler: app.lambdaToSlackHandler
      Runtime: nodejs14.x
      Events:
        SNS: # Alarm triggers the function
          Type: SNS
          Properties:
            Topic: !Ref AlarmTopic
        
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.helloHandler
      Runtime: nodejs14.x
      AutoPublishAlias: live #Maybe set the env???
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref HelloWorldAPI
            Path: /hello
            Method: get
      DeploymentPreference:
        Type: Canary10Percent5Minutes 
        Alarms:
          - !Ref HelloWorldFunctionAliasErrorAlarm       
       
  # --- Function Alarm Alias
  HelloWorldFunctionAliasErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: Errors
      Namespace: AWS/Lambda
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Period: 60
      Statistic: Sum
      Threshold: 2
      AlarmName: Error found 
      AlarmDescription: Fire alarm if more than 3 errors occur in any 60 second period
      TreatMissingData: notBreaching #https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html#alarms-and-missing-data
      Dimensions:
        - Name: Resource
          Value: !Sub "${HelloWorldFunction}:live"
        - Name: FunctionName
          Value: !Ref HelloWorldFunction
      AlarmActions:
        - !Ref AlarmTopic
